#!/usr/bin/bash
CC=gcc
SRC = main.c school.c
OBJ = main.o school.o
NAME = school

all: $(NAME)
	$(CC) $(SRC) -o $(NAME)

main.o: main.c
	$(CC) -c main.c

school.o: school.c
	$(CC) -c school.c
clean:
	rm *.o $(NAME)
