#!/usr/bin/bash
CC = gcc
SRC = main.c school.c
OBJ = $(SRC:.c=.o)
NAME = school
RM = make clean
all: $(OBJ)
	$(CC) $(OBJ) -o $(NAME)

clean: $(RM)
	rm *.~ *.swp

oclean: $(RM)
	rm *.o $(NAME)

fclean: $(RM)
	rm *.o $(NAME) *.~ *.swp
